
DROP TABLE [dbo].[ShopItemCourses]
DROP TABLE [dbo].[OwnedItems]
DROP TABLE [dbo].[TagScores]
DROP TABLE [dbo].[ItemTags]
DROP TABLE [dbo].[ShopItems]
DROP TABLE [dbo].[UserRoles]
DROP TABLE [dbo].[Questions]
DROP TABLE [dbo].[Edges]
DROP TABLE [dbo].[StudentLessons]
DROP TABLE [dbo].[Reviews]
DROP TABLE [dbo].[Lessons]
DROP TABLE [dbo].[Courses]
DROP TABLE [dbo].[CourseInstructors]
DROP TABLE [dbo].[Instructors]
DROP TABLE [dbo].[Categories]
DROP TABLE [dbo].[Students]
DROP TABLE [dbo].[Roles]
DROP TABLE [dbo].[Enrollments]
DROP TABLE [dbo].[CourseInstructors]

DROP TABLE [dbo].[CUsers]
DROP TABLE [dbo].[AspNetRoles]
DROP TABLE [dbo].[AspNetUserClaims]
DROP TABLE [dbo].[AspNetUserLogins]
DROP TABLE [dbo].[AspNetUserRoles]
DROP TABLE [dbo].[AspNetUsers]
DROP TABLE [dbo].[BlogPosts]